# -*- coding: utf-8 -*-
"""IA_Ejercicio3_EvaZamora_1851761.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/EvaZamora/d866e0b8bdc1ace8de8ecfddd610e6cf/-ia_ejercicio3_evazamora_1851761.ipynb

Actividad 3: Ejercicios Introducción Python Segunda Parte
Eva Paola Zamora Gutiérrez 1851761
Jueves N4-N6
"""

#Ejercicio 1
#1.1 Piensa en 7 comidas diferente que te gusten. Implementa un programa que pregunte por las 7 comidas, las almacene en una lista y que posteriermente imprima cada una de ellas utilizando uno de los ciclos comentados en clase. 
#Comidas: Pizza, Spaguetti, Ensalada, Crema de Broccoli, Pozole, Enchiladas, Sopes

lista = []

print("Piensa en 7 de tus comidas preferidas.\n")

i = 0
while i < 7:
  comidas = input("Ingresa una de tus comidas: ")
  lista.append(comidas)
  i += 1

print("\nTus comidas favoritas son:")
j = 0
x=0
while j < 7:
  print(lista[x])
  j += 1
  x += 1

# Modifica el ejercicio 1.1 para que imprima cada una de las comidas favoritas junto con una oracición inicial: "Una de mis comidas favoritas es [comida1]".
lista = []

print("Piensa en 7 de tus comidas preferidas.\n")

i = 0
while i < 7:
  comidas = input("Ingresa una de tus comidas: ")
  lista.append(comidas)
  i += 1

j = 0
x=0
while j < 7:
  print("\nUna de mis comidas favoritas es:", lista[x])
  j += 1
  x += 1

#Ejercicio 2
#Crear un juego de piedra, papel o tijera de dos jugadores. El programa preguntará por la opción del jugador 1 y la opción del jugador 2 y dará como resultado quien ganó el juego. 

print("Comenzará el juego de piedra, papel o tijera...")
print("Instrucciones:\nComenzará eligiendo el jugador 1 y a continuación, el jugador 2.\nYa definida la elección no hay marcha atrás, se anunciará el ganador.\n*Recuerda usar minúsculas para dar a conocer su opción.")
print("¡¡Empecemos!!")

a = input("Jugador 1 escoge:")
b = input("Jugador 2 escoge:")

if a == b:
  print("Ambos jugadores quedan empatados.")
if a == "piedra" and b == "papel":
  print("Jugador 2 gana.")
if a == "piedra" and b == "tijera":
  print("Jugador 1 gana.")
if a == "papel" and b == "piedra":
  print("Jugador 1 gana.")
if a == "papel" and b == "tijera":
  print("Jugador 2 gana.")
if a == "tijera" and b == "piedra":
  print("Jugador 2 gana.")
if a == "tijera" and b == "papel":
  print("Jugador 1 gana.")

#Ejercicio 3
#Implementar un programa que imprima el siguiente patron:
#123456
#12345
#1234
#123
#12
#1
#12
#123
#1234
#12345
#123456

     
num = 1
 
    
for i in range(0, 6):
     
        
    num = 1
     
        
            
    for j in range(0, i+1):
         
                
        print(num, end=" ")
         
            
        num = num + 1
     
        
    print("\r")    

 #Se buscó algo similar para poder llevarlo a cabo y aún así no pude realizarlo, seguiré revisándolo para poder lograr llevarlo a cabo.
 #Link de referencia https://es.acervolima.com/2021/02/09/programas-para-imprimir-patrones-piramidales-en-python/#:~:text=Los%20patrones%20se%20pueden%20imprimir%20en%20Python%20usando,patrones%20num%C3%A9ricos%2C%20patrones%20alfab%C3%A9ticos%20o%20patrones%20de%20estrellas.